networks:
  monitoring:
    driver: bridge

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: >
      - python init_db.py
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    container_name: postgres_container
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - log_destination=stderr
      - logging_collector=on
      - log_directory=./logs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    networks:
      - monitoring
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db:/var/lib/postgresql/data